CREATE TABLE MEDICAMENTATIE(
ID_MEDICAMENT INT PRIMARY KEY NOT NULL,
BOALA VARCHAR(255) NOT NULL ,
Perioada_Tratament datetime NOT NULL,
DozaPezi float,
TipMedicament VARCHAR(255),
MEDICAMENTE VARCHAR(255),

);
INSERT INTO MEDICAMENTATIE(ID_MEDICAMENT,BOALA,Perioada_Tratament,DozaPezi,TipMedicament,MEDICAMENTE) VALUES(1,'AVC',2024-04-12 ,2.5,'PENTRU INIMA','IMPOTRIVA HIPERTENSIUNII')
INSERT INTO MEDICAMENTATIE(ID_MEDICAMENT,BOALA,Perioada_Tratament,DozaPezi,TipMedicament,MEDICAMENTE) VALUES(2,'PNEUMONIE',2024-04-12,1.7,'PENTRU PLAMANI','EXPECTORANTE')
INSERT INTO MEDICAMENTATIE(ID_MEDICAMENT,BOALA,Perioada_Tratament,DozaPezi,TipMedicament,MEDICAMENTE) VALUES(3,'DIABET',2009-04-25,6.5,'REGLAREA GLICEMIEI','IMPOTRIVA DIABETULUI')
INSERT INTO MEDICAMENTATIE(ID_MEDICAMENT,BOALA,Perioada_Tratament,DozaPezi,TipMedicament,MEDICAMENTE) VALUES(4,'CANCER ',2003-04-12,10,'PENTRU CANCER PULMONAR','CITOSTATICE')
INSERT INTO MEDICAMENTATIE(ID_MEDICAMENT,BOALA,Perioada_Tratament,DozaPezi,TipMedicament,MEDICAMENTE) VALUES(5,'CANDIDA',2007-04-12,2.5,'PENTRU ADMINISTRARE PE CALE BUCALA','IMPOTRIVA INFECTIILOR GINGIVALE')
INSERT INTO MEDICAMENTATIE(ID_MEDICAMENT,BOALA,Perioada_Tratament,DozaPezi,TipMedicament,MEDICAMENTE) VALUES(6,'TULBURĂRI PSIHOLOGICE',2023-07-30,8.7,'PSIHOTERAPEUTICE','IMPOTRIVA DEMENȚEI')
INSERT INTO MEDICAMENTATIE(ID_MEDICAMENT,BOALA,Perioada_Tratament,DozaPezi,TipMedicament,MEDICAMENTE) VALUES(7,'TULBURĂRI NERVOASE',2023-07-30,8.7,'PSIHOTERAPEUTICE','IMPOTRIVA DEMENȚEI')


--UPDATE MEDICAMENTATIE
--SET DozaPezi=1
--WHERE DozaPezi<=2 


--SELECT BOALA FROM MEDICAMENTATIE WHERE LEFT(BOALA,1)='P'
--UNION
--SELECT BOALA FROM MEDICAMENTATIE WHERE LEFT(BOALA,1)='C'


--SELECT BOALA FROM MEDICAMENTATIE
--INTERSECT 
--SELECT BOALA FROM TRATAMENT

--SELECT BOALA FROM MEDICAMENTATIE
--EXCEPT
--SELECT BOALA FROM TRATAMENT



