CREATE TABLE TRATAMENT(
PACIENTII_ID INT NOT NULL,
BOALA VARCHAR(255),
GRAVITATE INT,
MEDICAMENTE_TIP VARCHAR(255),
ID_MEDICAMENT INT,
FOREIGN KEY (ID_MEDICAMENT) REFERENCES MEDICAMENTATIE(ID_MEDICAMENT),
PROVENIENTA VARCHAR(255),
FOREIGN KEY (PACIENTII_ID) REFERENCES PACIENTII(ID),--
CONSTRAINT PK_DetaliiBoala PRIMARY KEY (PACIENTII_ID,ID_MEDICAMENT),
);
INSERT INTO TRATAMENT(PACIENTII_ID,ID_MEDICAMENT,BOALA,GRAVITATE,MEDICAMENTE_TIP,PROVENIENTA) VALUES (1,2,'AVC',3,'IMPOTRIVA HIPERTENSIUNII','stres')
INSERT INTO TRATAMENT(PACIENTII_ID,ID_MEDICAMENT,BOALA,GRAVITATE,MEDICAMENTE_TIP,PROVENIENTA) VALUES (2,4,'CANCER',4,'CITOSTATICE','CUMUL DE FACTORI TOXICI')
INSERT INTO TRATAMENT(PACIENTII_ID,ID_MEDICAMENT,BOALA,GRAVITATE,MEDICAMENTE_TIP,PROVENIENTA) VALUES (5,6,'TULBURÃRI PSIHOLOGICE',6,'PSIHOTERAPEUTICE',' ')
INSERT INTO TRATAMENT(PACIENTII_ID,ID_MEDICAMENT,BOALA,GRAVITATE,MEDICAMENTE_TIP,PROVENIENTA) VALUES (7,3,'DIABET',7,'IMPOTRIVA DIABETULUI',NULL)
INSERT INTO TRATAMENT(PACIENTII_ID,ID_MEDICAMENT,BOALA,GRAVITATE,MEDICAMENTE_TIP,PROVENIENTA) VALUES (6,3,'DIABET',7,'IMPOTRIVA DIABETULUI',NULL)
--UPDATE TRATAMENT
--SET PROVENIENTA='STRES'
--WHERE PROVENIENTA='stres'
--DELETE FROM TRATAMENT WHERE PROVENIENTA IS NULL

--UPDATE TRATAMENT
--SET GRAVITATE=2
--WHERE BOALA LIKE 'T%'

 --This query uses an `INNER JOIN` to find medication types and daily dosages from `MEDICAMENTATIE` that are associated with treatments in `TRATAMENT`.
-- The `INNER JOIN` only returns rows where there is a match in both `MEDICAMENTATIE` and `TRATAMENT`.

--SELECT TipMedicament,DozaPezi
--FROM MEDICAMENTATIE
--INNER JOIN TRATAMENT ON MEDICAMENTATIE.ID_MEDICAMENT=TRATAMENT.ID_MEDICAMENT;

-- This query uses a `RIGHT JOIN` to get all rows from `TRATAMENT` and the matching rows from `MEDICAMENTATIE`.
-- If a medication in `TRATAMENT` has no matching entry in `MEDICAMENTATIE`, the medication fields from `MEDICAMENTATIE` will be NULL.

--SELECT TRATAMENT.ID_MEDICAMENT,TipMedicament,MEDICAMENTATIE.BOALA   FROM MEDICAMENTATIE
--RIGHT JOIN TRATAMENT ON MEDICAMENTATIE.ID_MEDICAMENT=TRATAMENT.ID_MEDICAMENT