CREATE TABLE PACIENTII (
ID INT NOT NULL,
NUME VARCHAR(255) NOT NULL ,
PRENUME VARCHAR(255) NOT NULL,
BOALA VARCHAR(255) NOT NULL,
PRIMARY KEY(ID),
);
INSERT INTO PACIENTII(ID,NUME,PRENUME, BOALA) VALUES (1,'DWDW','WDWED','ASTM')
INSERT INTO PACIENTII(ID,NUME,PRENUME, BOALA) VALUES (3,'Ionescu','Ana','EPILEPSIE')
INSERT INTO PACIENTII(ID,NUME,PRENUME, BOALA) VALUES (4,'Popescu','Ionel','AVC')
INSERT INTO PACIENTII(ID,NUME,PRENUME, BOALA) VALUES (5,'Onea','Alex','ALERGIE')
INSERT INTO PACIENTII(ID,NUME,PRENUME, BOALA) VALUES (2,'Oprea','Dan','CANCER')
INSERT INTO PACIENTII(ID,NUME,PRENUME, BOALA) VALUES (6,'Dragomir','Aurel','DIABET')
INSERT INTO PACIENTII(ID,NUME,PRENUME,BOALA) VALUES (9,'xulescu','jfbjsfw','EPILEPSIE')

--UPDATE PACIENTII
--SET BOALA = 'CANDIDA'
--WHERE BOALA='alergie' or BOALA='ASTM';
--UPDATE PACIENTII
--SET BOALA = 'AVC'
--WHERE BOALA='AVC';
INSERT INTO PACIENTII(ID,NUME,PRENUME,BOALA) VALUES (7,'Popescu','Ana','AVC')
INSERT INTO PACIENTII(ID,NUME,PRENUME,BOALA) VALUES (8,'Zepciuc','Denisa',' TULBURÃRI PSIHOLOGICE')

--SELECT  NUME FROM PACIENTII
--INTERSECT
--SELECT BOALA FROM TRATAMENT
  
-- This query uses a `LEFT JOIN` to combine `PACIENTII` and `MEDICAMENTATIE`.
-- It retrieves all patients (from PACIENTII) and attempts to match each patient's illness with medications in MEDICAMENTATIE.

--SELECT ID,NUME,PRENUME,DozaPezi
--FROM PACIENTII
--LEFT JOIN MEDICAMENTATIE
--ON PACIENTII.BOALA=MEDICAMENTATIE.BOALA
--ORDER BY MEDICAMENTATIE.DozaPezi

-- This query uses a `FULL JOIN` across three tables: `PACIENTII`, `TRATAMENT`, and `DETALIIPACIENT`.
-- A `FULL JOIN` returns all records where there is a match in either `PACIENTII` or `TRATAMENT` or `DETALIIPACIENT`.

--SELECT DETALIIPACIENT.CNP,PACIENTII.NUME,TRATAMENT.BOALA FROM TRATAMENT
--FULL JOIN PACIENTII ON PACIENTII.ID=TRATAMENT.PACIENTII_ID
--FULL JOIN DETALIIPACIENT ON DETALIIPACIENT.PACIENTII_ID=PACIENTII.ID

-- Query 1: Find patients with illnesses for which medication is specified in `MEDICAMENTATIE`.
--SELECT NUME, PRENUME, BOALA
--FROM PACIENTII
--WHERE BOALA IN (SELECT BOALA FROM MEDICAMENTATIE)
--ORDER BY NUME;

-- Query 2: List treatments where the patient is listed in `PACIENTII`.
--SELECT BOALA, GRAVITATE, MEDICAMENTE_TIP
--FROM TRATAMENT t
--WHERE EXISTS (SELECT * FROM PACIENTII p WHERE p.ID != t.PACIENTII_ID);
 
 -- Query 3: Find the average dose per treatment type.
--SELECT MEDICAMENTE_TIP, AVG(DozaPezi) AS Avg_Dose
--FROM (SELECT MEDICAMENTE_TIP, DozaPezi FROM TRATAMENT JOIN MEDICAMENTATIE ON TRATAMENT.ID_MEDICAMENT = MEDICAMENTATIE.ID_MEDICAMENT) AS TreatmentDosages
--GROUP BY MEDICAMENTE_TIP
--ORDER BY Avg_Dose DESC;

-- Query 4: Count of treatments by illness.
--SELECT BOALA, COUNT(*) AS Treatment_Count
--FROM TRATAMENT
--GROUP BY BOALA;


-- Query 5: List illnesses with an average gravity above 4.
--SELECT BOALA, AVG(GRAVITATE) AS Avg_Gravity
--FROM TRATAMENT
--GROUP BY BOALA
--HAVING AVG(GRAVITATE) > 1;

-- Query 6: List treatments where total dosage exceeds the overall average dosage.
--SELECT TipMedicament, SUM(DozaPezi) AS Total_Dosage
--FROM MEDICAMENTATIE
--GROUP BY TipMedicament
--HAVING SUM(DozaPezi) > (SELECT AVG(DozaPezi) FROM MEDICAMENTATIE);

-- Query 7: List treatments with specific severity and type conditions.
--SELECT PACIENTII_ID, BOALA, GRAVITATE, MEDICAMENTE_TIP
--FROM TRATAMENT
--WHERE GRAVITATE > 2 AND (MEDICAMENTE_TIP = 'IMPOTRIVA DIABETULUI' OR MEDICAMENTE_TIP = 'CITOSTATICE') AND NOT BOALA = 'AVC'
--ORDER BY PACIENTII_ID;

-- Query 8: Select top 3 illnesses with the most unique treatments.
--SELECT TOP 3 BOALA, COUNT(DISTINCT ID_MEDICAMENT) AS Unique_Treatments
--FROM TRATAMENT
--GROUP BY BOALA
--ORDER BY Unique_Treatments DESC;
