CREATE TABLE Logs (
    LogID INT IDENTITY(1,1) PRIMARY KEY,
    TriggerDate DATETIME NOT NULL DEFAULT GETDATE(),
    TriggerType VARCHAR(10) NOT NULL,
    NameAffectedTable VARCHAR(255) NOT NULL,
    NoAMDRows INT NOT NULL
);