-- Step 4: Test Triggers
-- INSERT Example
INSERT INTO PACIENTII (ID, NUME, PRENUME, BOALA)
VALUES (18, 'TestName2', 'TestSurname2', 'TestBoala2'),
(17, 'TestName12', 'TestSurname12', 'TestBoala12');
INSERT INTO PACIENTII (ID, NUME, PRENUME, BOALA)
VALUES (16, 'TestName1', 'TestSurname1', 'TestBoala1');

-- UPDATE Example
UPDATE PACIENTII
SET NUME = 'UpdatedName'
WHERE ID = 1;

-- DELETE Example
DELETE FROM PACIENTII
WHERE ID = 9;

-- Check Logs
SELECT * FROM Logs;

INSERT INTO MEDICAMENTATIE (ID_MEDICAMENT, BOALA, Perioada_Tratament, DozaPezi, TipMedicament, MEDICAMENTE)
VALUES (12, 'TestBoala', '2024-01-01', 2.5, 'TEST', 'TEST_MED');

INSERT INTO TRATAMENT (PACIENTII_ID, ID_MEDICAMENT, BOALA, GRAVITATE, MEDICAMENTE_TIP, PROVENIENTA)
VALUES (1, 12, 'TestBoala', 5, 'TEST', 'TEST');

-- Test Update Trigger for TRATAMENT
UPDATE TRATAMENT
SET GRAVITATE = 10
WHERE ID_MEDICAMENT = 12;

-- Test Delete Trigger for TRATAMENT
DELETE FROM TRATAMENT
WHERE ID_MEDICAMENT = 12;

-- Verify Logs for TRATAMENT
SELECT * FROM Logs;